# commit to be tagged for new release
commit = "HEAD"

project_name = "CAPI Bootstrap Provider Talos"
github_repo = "siderolabs/cluster-api-bootstrap-provider-talos"
match_deps = "^github.com/(siderolabs/[a-zA-Z0-9-]+)$"

# previous release
previous = "v0.6.11"

pre_release = true

[notes]

[notes.CAPI]
    title = "CAPI"
    description = """\
CABPT is now compatible with CAPI v1.12.0+ (v1beta2).
"""

preface = """\
"""
