# commit to be tagged for new release
commit = "HEAD"

project_name = "CAPI Bootstrap Provider Talos"
github_repo = "siderolabs/cluster-api-bootstrap-provider-talos"
match_deps = "^github.com/(siderolabs/[a-zA-Z0-9-]+)$"

# previous release
previous = "v0.6.1"

pre_release = false

preface = """\
"""

[notes]

    [notes.talos]
        title = "Talos 1.5"
        description = """\
CABPT now supports machine configuration generation for Talos 1.5.
"""
